### ISSUE TITLE
Error: 'create_cluster'

### ISSUE THREAD

**Issue by zhengjiji456** [tidyverse/multidplyr#101]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
I prepared my codes below

multidplyr::create_cluster() %>%
  cluster_library(c('r3PG', 'purrr', 'dplyr', 'tidyr')) %>%
  cluster_copy( r3pg_grid ) %>%
  cluster_copy( species.grid ) %>%
  cluster_copy( thinn.grid ) %>%
  cluster_copy( param.draw )

However, I got an error message
Error: 'create_cluster' is not an exported object from 'namespace:multidplyr'

Was this function creat_cluster removed? (https://www.rdocumentation.org/packages/multidplyr/versions/0.0.0.9000/topics/create_cluster)
  
``r
# insert reprex here
```

**Comment by WentingCao** [comment]
Hi I encountered the same problem. Have you ever solved it ?

**Comment by hadley** [comment]
It sounds like you're using an old version of the instructions: `new_cluster()` the function you should now be using — https://multidplyr.tidyverse.org/#usage.
