### ISSUE TITLE
Is this package completed yet?

### ISSUE THREAD

**Issue by McChickenNuggets** [tidyverse/multidplyr#103]
I get an error saying that multidplyr is not available for my current R Version. 
and I encounter Warning in install.packages :
  package ‘multidplyr’ is not available (for R version 3.6.3)

So, I try to call remotes::install_github("tidyverse/multidplyr"), then I have the following error
Error: Failed to install 'multidplyr' from GitHub:
  ERROR: failed to lock directory ‘C:\Users\Jaune\Documents\R\win-library\3.6’ for modifying
Try removing ‘C:\Users\Jaune\Documents\R\win-library\3.6/00LOCK’

So, I remove 00LOCK and rerun it, Then I have
package ‘digest’ successfully unpacked and MD5 sums checked
cannot remove prior installation of package ��digest��problem copying C:\Users\Jaune\Documents\R\win-library\3.6\00LOCK\digest\libs\x64\digest.dll to C:\Users\Jaune\Documents\R\win-library\3.6\digest\libs\x64\digest.dll: Permission deniedrestored ��digest��package ‘glue’ successfully unpacked and MD5 sums checked
package ‘vctrs’ successfully unpacked and MD5 sums checked
package ‘rlang’ successfully unpacked and MD5 sums checked
cannot remove prior installation of package ��rlang��problem copying C:\Users\Jaune\Documents\R\win-library\3.6\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\Jaune\Documents\R\win-library\3.6\rlang\libs\x64\rlang.dll: Permission deniedrestored ��rlang��
```

**Comment by hadley** [comment]
It sounds like you have packages loaded in other R sessions — I'd recommend closing all open R/RStudio sessions and trying again in a fresh session.
