### ISSUE TITLE
multidplyr not finding dplyr verbs not exported as S3methods

### ISSUE THREAD

**Issue by isaac-florence** [tidyverse/multidplyr#104]
Using multidplyr with further dplyr functions, multidplyr can't find case_when, if_else, lag, lead, first, etc. When both dplyr and multidplyr are loaded and applying these functions within mutate, they cannot be found unless including dplyr::

Example that doesn't work:
```
linelist %>%
    partition(cluster) %>%
    mutate(test = case_when(date1 > lag(date1) ~ "remove_flag") %>%
    collect()
```
Example that does work but could/should be faster
```
linelist %>%
    partition(cluster) %>%
    mutate(test = dplyr::case_when(date1 > dplyr::lag(date1) ~ "remove_flag")%>%
    collect()
```

Naturally calling these functions from the namespace has a time cost so I can't imagine this is the most efficient form of doing this. I tried loading dplyr to the cluster which appeared successful but then multidplyr couldn't find `collect()`. 

I then tried forking this repo and these functions as S3 methods in a similar style to the dplyr-single script ([see comparison here](https://github.com/tidyverse/multidplyr/compare/master...isaac-florence:master)) however multidplyr still couldn't find these functions.

I imagine this is more an issue in my understanding than an issue with the code but would be grateful for an explanation or pointers for correct inclusion of these further verbs, please!
As an aside, even when using dplyr:: ahead of these functions, multidplyr is already saving time on our processes so very grateful for this. Are there plans for its further development?

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by isaac-florence** [comment]
Here is my reprex. Minor issue in {rlang} not recognising the errors but the messages are function not found

``` r
library(multidplyr)
library(dplyr, warn.conflicts = F)



df <- data.frame(date1 = seq.Date(as.Date("2020-01-01"), as.Date("2020-12-31"), by = "day"),
                 id = rep(c("a", "b"), times = 183))

cluster <- new_cluster(2)

##won't work
df %>% 
  group_by(id) %>% 
  partition(cluster) %>% 
  mutate(flag = case_when(date1 > lag(date1) ~ "flag")) %>% 
  collect()
#> Error: Computation failed

rlang::last_error()
#> Error: Can't show last error because no error was recorded yet

rlang::last_trace()
#> Error: Can't show last error because no error was recorded yet

##will work
df %>% 
  group_by(id) %>% 
  partition(cluster) %>% 
  mutate(flag = dplyr::case_when(date1 > dplyr::lag(date1) ~ "flag")) %>% 
  collect()
#> # A tibble: 366 x 3
#> # Groups:   id [2]
#>    date1      id    flag 
#>    <date>     <chr> <chr>
#>  1 2020-01-01 a     <NA> 
#>  2 2020-01-03 a     flag 
#>  3 2020-01-05 a     flag 
#>  4 2020-01-07 a     flag 
#>  5 2020-01-09 a     flag 
#>  6 2020-01-11 a     flag 
#>  7 2020-01-13 a     flag 
#>  8 2020-01-15 a     flag 
#>  9 2020-01-17 a     flag 
#> 10 2020-01-19 a     flag 
#> # ... with 356 more rows


detach("package:multidplyr", unload = T)
detach("package:dplyr", unload = T)

rm(cluster, df)
```

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
It doesn't look like you've loaded dplyr on the workers?

**Comment by isaac-florence** [comment]
<<face palms>> The first time I tried that I got an error as it couldn't find collect() but clearly I should have been more persistent. Sorry...!

Although that does lead into the follow up of this question: why would adding imported functions in a similar fashion to what you have done in the dplyr-single script not work? See comparison [here](https://github.com/tidyverse/multidplyr/compare/master...isaac-florence:master)

Thank you for producing this package, sorry you have to cope with foolish questions like this!

**Comment by hadley** [comment]
I think it only really makes sense for verbs that are applied to data frames — that's what dplyr (and hence multidplyr) is all about. (Other systems have tried to parallelise individual vector functions as in your code, but I don't think they ever fully succeed due to the challenges to matching up the vectors across the workers)
