### ISSUE TITLE
Error when getting 2010 census block-level data for an area in Alaska

### ISSUE THREAD

**Issue by chrismp** [tidyverse/multidplyr#120]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

When I run this code...

```r
get_decennial(
  geography = 'block',
  county = '158',
  state = '02',
  geometry = T,
  variables = 'P001001',
  cache_table = T
)
```

I get this error...
```

Getting data from the 2010 decennial Census
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
No encoding supplied: defaulting to UTF-8.
Error : Your API call has errors.  The API message returned is .
Using Census Summary File 1
Error in UseMethod("gather") : 
  no applicable method for 'gather' applied to an object of class "character"
```

**Comment by hadley** [comment]
I think you filed this in the wrong place.
