### ISSUE TITLE
Consider making `qs` a suggested package

### ISSUE THREAD

**Issue by michaelquinn32** [tidyverse/multidplyr#135]
`qs` comes with a lot of native dependencies that can be a bit of a challenge to manage (e.g. 5 libraries in this package and PCRE2 in stringfish).

Since the API is meant to mostly reproduce what base R provides with readRDS and saveRDS, is it possible to make qs a suggestion? You get faster serialization if have it, but you don't have to rely on it if you don't.

Thanks!

**Comment by hadley** [comment]
My recollection is that qs makes a really big difference here; so much so that there's much less benefit to using multidplyr without it. I think that means it's unlikely we'd move it to suggests.
