### ISSUE TITLE
Add Verbose Option to Track Progress

### ISSUE THREAD

**Issue by pmenaq-new** [tidyverse/multidplyr#158]
I would like to request a feature that allows users to monitor the progress of operations when using multidplyr. It would be helpful to have a verbose option or any other mechanism that provides feedback on the state of the process as it runs.

Use Case:

Currently, when running operations across multiple workers, it is not clear how far along the process is or if it has stalled. Adding a verbose mode that prints out progress updates would improve user experience, especially for long-running tasks.

Example:

```
cluster <- multidplyr::new_cluster(4)
cluster_library(cluster, "dplyr")

# Enable verbose to see progress
data %>%
  partition(cluster) %>%
  mutate(new_var = some_expensive_operation(.)) %>%
  collect(verbose = TRUE)
```

In this case, verbose = TRUE would provide output showing progress per worker or iteration.

Thank you for considering this feature.

**Comment by hadley** [comment]
Unfortunately cross-process progress bars are really hard to do 😞  So this is currently out of scope for multidplyr.
