### ISSUE TITLE
installing older version of multidplyr

### ISSUE THREAD

**Issue by samkhan1** [tidyverse/multidplyr#78]
Is there a way to install an older version (<0.0.0.9000) that has `create_cluster` function and uses the older methods around `cluster_copy` instead of using `cluster_asign`

and could you create a changelog. thank you.

**Comment by Courvoisier13** [comment]
I have the same issue. The current version requires R>3.5 that has the qs package, and I can only use 3.4.4.  I tried 
```
githubinstall::gh_install_packages(packages = "multidplyr",
                                   ref = "3e65c2c9d5011fa34d18965308e5c52326a6d3c4",
                                   force = T)
```
and installed the 2017 commit 3e65c2c9d5011fa34d18965308e5c52326a6d3c4 see https://github.com/tidyverse/multidplyr/commits/master?after=51b772f980efe936233d97a6f0dd61543b3b7818+34 for more details

**Comment by ldanai** [comment]
I have tried this and it works fine: 

```
library(remotes)
remotes::install_github("tidyverse/multidplyr#10")
```

**Comment by hadley** [comment]
I just made a tag so you can do `remotes::install_github("tidyverse/multdiplyr@beta")`
