### ISSUE TITLE
Partition doesn't allow the use of pivot_longer ... says map_lgl is missing data

### ISSUE THREAD

**Issue by baldeagle** [tidyverse/multidplyr#86]
When a dataframe is partitioned by multidplyr, I would like to be able to use pivot_longer / pivot_wider on it.  My pattern is to take the data and make it long, then make it wide by a different variable (e.g. logs on two dates, where all the columns are gathered into key/value pairs for longer data, and then spread by the log date for comparison purposes).

```r
data(mtcars)
cl <- new_cluster(5)
mtcars %>% partition(cl) %>% pivot_longer(c(cyl,gear)) %>% collect() #fails
#> Error in map_lgl(.x, .p, ...) : object 'cyl' not found
mtcars %>% group_by(cyl,gear) %>% partition(cl) %>% pivot_longer(c(cyl,gear)) %>% collect() #also fails
#> Error in map_lgl(.x, .p, ...) : object 'cyl' not found"
```

**Comment by baldeagle** [comment]
Is there a place or tutorial that I could review to provide more assistance with this issue?

**Comment by baldeagle** [comment]
I would like to assist with this bug, but don't know where to start.  Please provide guidance, and I'll try to tackle it myself.

**Comment by hadley** [comment]
multidplyr currently only supports dplyr functions, not tidyr functions. I'd prefer to wait until absolutely certain that multidplyr is the correct design before adding tidyr support.
